// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeMnHlftSzEWdmnhSDWtb97GHPeq7q3V8',
    appId: '1:314617645972:android:65ece261e887ca85ccdd81',
    messagingSenderId: '314617645972',
    projectId: 'ridam-chat-b392d',
    storageBucket: 'ridam-chat-b392d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvFUV6F6T0CjzJ_FXqbbqFV-3JiBVqYvM',
    appId: '1:314617645972:ios:c7b9daf87be3dcd2ccdd81',
    messagingSenderId: '314617645972',
    projectId: 'ridam-chat-b392d',
    storageBucket: 'ridam-chat-b392d.appspot.com',
    androidClientId: '314617645972-fpbr5ee20je3ai9eammjrn3ohm2qtp26.apps.googleusercontent.com',
    iosClientId: '314617645972-0kfg1ih33vr63cj0o9hacvg3a6kasg62.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridamchat',
  );
}
